config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  passwords: "public/passwords",
  sessions: 'public/sessions'
  }


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get 'about' => 'public/homes#about', as: 'about'
  get 'admin' => 'admin/homes#top'


  namespace :public do
    resources :homes, only: [:top, :about] do
    end
    resources :posts, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
      #投稿検索機能
      get 'search' => 'posts#search', on: :collection
      #ブックマーク機能(good)
      post 'good/:id' => 'goods#create', as: 'create_good'
      delete 'good/:id' => 'goods#destroy', as: 'destroy_good'
      #ブックマーク機能(go)
      post 'go/:id' => 'gos#create', as: 'create_go'
      get 'go/:id' => 'gos#index', as: 'index_go'
      delete 'go/:id' => 'gos#destroy', as: 'destroy_go'
      #コメント機能
      resources :comments, only: [:create, :destroy]
      #地図機能
      get 'map' => 'posts#map'
    end
    #ゲストログイン機能
    devise_scope :customer do
      post "customers/guest_sign_in", to: "sessions#guest_sign_in"
    end
    resources :customers, only: [:show, :edit, :update] do
      get 'inf_show' => 'customers#inf_show'
      get 'inf_edit' => 'customers#inf_edit'
      patch 'inf_update' => 'customers#inf_update'
      #ユーザー検索機能
      get 'search' => 'customers#search', on: :collection
      #退会機能
      get 'confirm' => 'customers#confirm'
      patch 'withdrow' => 'customers#withdrow'
    end
    resources :follows, only: [:create, :destroy] do
      get 'follower/:id' => 'follows#follower', as: 'follower'
      get 'followed/:id' => 'follows#followed', as: 'followed'
    end
    resources :goods, only: [:index] do
    end
    resources :goes, only: [:index] do
    end
    resources :genres, only: [:index] do
    end
 end

namespace :admin do
  resources :homes, only: [:top] do
  end
  resources :posts, only: [:index, :show, :destroy] do
  end
  resources :customers, only: [:index, :show, :edit, :update] do
  end
  resources :genres, only: [:index, :create, :edit, :update] do
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

#コメント機能・いいね・行ってみたい
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :goods
  has_many :gos

  def good_find(post_id)
    goods.where(post_id: post_id).exists?
  end

  def go_find(post_id)
    gos.where(post_id: post_id).exists?
  end

#フォロー機能
  # フォローをした、されたの関係
  has_many :follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followeds, through: :follows, source: :followed
  has_many :followers, through: :reverse_of_follows, source: :follower

  #フォローしたときの処理
  def followed(customer_id)
    # binding.pry
    follows.create(followed_id: customer_id)
  end
  # フォローを外すときの処理
  def unfollow(customer_id)

    follows.find_by(followed_id: customer_id).destroy
  end
  # フォローしているか判定
  def followed?(customer)
    followeds.include?(customer)
  end


#ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
    end
  end


#ユーザー検索機能
  def self.search(keyword)
    where(["last_name like? OR first_name like? OR user_name like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(7)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customers_path
  end

  private

    def customer_params
        params.require(:customer).permit(:first_name, :last_name, :last_name_kana,
                                         :first_name_kana, :email, :encrypted_password,
                                          :telephone_number,:is_deleted, :image)
    end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h4>admin customers edit</h4>
<div class="container ppp col-lg-8">
  <div class="row">
    <h3 class="page-name">
      <strong>
        <%= @customer.first_name %><%= @customer.last_name %>
      </strong>
        さんの
      <strong>
        会員詳細
      </strong>
    </h3>
  </div>

  <div class="row">
    <div class="col-lg-10">
      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
      <table>
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= f.text_field :first_name , class: 'form-control first_name' %></td>
          <td><%= f.text_field :last_name , class: 'form-control last_name' %></td>
          </td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= f.text_field :first_name_kana , class: 'form-control first_name_kana' %></td>
          <td><%= f.text_field :last_name_kana , class: 'form-control last_name_kana' %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= f.text_field :postal_code , class: 'form-control postal_code' %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= f.text_field :address , class: 'form-control address' %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= f.text_field :telephone_number , class: 'form-control ' %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= f.email_field :email , class: 'form-control email' %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td class="td-statu">
            <%= f.radio_button :is_deleted, true %><label for="customer_is_deleted">退会</label>
            <%= f.radio_button :is_deleted, false %><label for="customer_is_deleted">有効</label>
          </td>
        </tr>
        <tr>
          <th></th>
          <td><%= f.submit'変更を保存' , class: 'btn btn-success' %></td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<h4>admin customers index </h4>

<div class="container ppp col-lg-8">
  <div class="row">
    <h3 class="page-name">会員一覧</h3>
  </div>

  <div class="row">
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id) do %>
              <p><%= customer.first_name %><%= customer.last_name %></p>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_deleted == true %>
              <p>退会</p>
            <% else %>
              <p>有効</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="paginate">
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<h4>admin customers show</h4>

<div class="container ppp col-lg-8">
  <div class="row">
    <h3 class="page-name">
      <strong>
        <%= @customer.first_name %><%= @customer.last_name %>
      </strong>
        さんの
      <strong>
        会員詳細
      </strong>
    </h3>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <table class="table table-hover table-inverse">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.first_name %><%= @customer.last_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.first_name_kana %><%= @customer.last_name_kana %></td>
        </tr>

        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td><% if @customer.is_deleted == true %>
                <p>退会</p>
              <% else %>
                <p>有効</p>
              <% end %>
          </td>
        </tr>
        <tr>
          <th></th>
          <td>
            <%= link_to edit_admin_customer_path(@customer) , class: 'btn btn-success' do %>
              <span>編集する</span>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>

</div>