config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  passwords: "public/passwords",
  sessions: 'public/sessions'
  }


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get 'about' => 'public/homes#about', as: 'about'
  get 'admin' => 'admin/homes#top'


  namespace :public do
    resources :homes, only: [:top, :about] do
    end
    resources :posts, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
      #投稿検索機能
      get 'search' => 'posts#search', on: :collection
      #ブックマーク機能(good)
      post 'good/:id' => 'goods#create', as: 'create_good'
      delete 'good/:id' => 'goods#destroy', as: 'destroy_good'
      #ブックマーク機能(go)
      post 'go/:id' => 'gos#create', as: 'create_go'
      get 'go/:id' => 'gos#index', as: 'index_go'
      delete 'go/:id' => 'gos#destroy', as: 'destroy_go'
      #コメント機能
      resources :comments, only: [:create, :destroy]
      #地図機能
      get 'map' => 'posts#map'
    end
    #ゲストログイン機能
    devise_scope :customer do
      post "customers/guest_sign_in", to: "sessions#guest_sign_in"
    end
    resources :customers, only: [:show, :edit, :update] do
      get 'inf_show' => 'customers#inf_show'
      get 'inf_edit' => 'customers#inf_edit'
      patch 'inf_update' => 'customers#inf_update'
      #ユーザー検索機能
      get 'search' => 'customers#search', on: :collection
      #退会機能
      get 'confirm' => 'customers#confirm'
      patch 'withdrow' => 'customers#withdrow'
    end
    resources :follows, only: [:create, :destroy] do
      get 'follower/:id' => 'follows#follower', as: 'follower'
      get 'followed/:id' => 'follows#followed', as: 'followed'
    end
    resources :goods, only: [:index] do
    end
    resources :goes, only: [:index] do
    end
    resources :genres, only: [:index] do
    end
 end

namespace :admin do
  resources :homes, only: [:top] do
  end
  resources :posts, only: [:index, :show, :destroy] do
  end
  resources :customers, only: [:index, :show, :edit, :update] do
  end
  resources :genres, only: [:index, :create, :edit, :update] do
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :image

#コメント機能・いいね・行ってみたい
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :goods
  has_many :gos
  has_many :genres

#投稿検索機能
  def self.search(keyword)
    where(["shop like? OR address like?", "%#{keyword}%", "%#{keyword}%"])
  end

#map機能
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def index
    @posts = Post.page(params[:page]).per(8)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<h4>admin_post_index</h4>
<div class="container ppp col-lg-8">
  <div class="row">
    <h3 class="page-name">投稿一覧</h3>
  </div>

  <% @posts.each do |post| %>
    <div class="row post">
      <div class="i_con col-lg-1">
        <% if post.customer.image.attached? %>
          <%= image_tag post.customer.image, size: "50x50" %>
        <% else %>
          <%= image_tag asset_path('no_image.jpg'), size: "50x50" %>
        <% end %>
      </div>

      <div class="user-name col-lg-11">
        <%= post.customer.user_name %>
      </div>

      <div class="photo mx-auto">
        <%=link_to public_post_path(post) do %>
          <% if post.image.attached? %>
            <%= image_tag post.image, size: "300x300" %>
          <% else %>
            <%= image_tag asset_path('no_image.jpg'), size: "300x300" %>
          <% end %>
        <% end %>
      </div>

      <div class="shop col-lg-11">
        <h3><%= post.shop %></h3>
      </div>
      <div class="address col-lg-5">
        <p>〒<%= post.postal_code %></br>
            　<%= post.address %></p>
      </div>
      <div class="good col-lg-3">
        <p>お気に入り <%= post.goods.count %>件</p>
      </div>
    </div>
  <% end %>

  <div class="paginate">
    <%= paginate @posts %>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container ppp col-lg-8">
  <div class="row">
    <div class="i_con">
      <%=link_to admin_customer_path(@post) do %>
        <% if @post.customer.image.attached? %>
          <%= image_tag @post.customer.image, size: "50x50" %>
        <% else %>
          <%= image_tag asset_path('no_image.jpg'), size: "50x50" %>
        <% end %>
      <% end %>
    </div>

    <div class="user-name">
      <%= @post.customer.user_name %>
    </div>

    <div class="shop-name col-lg-12">
      <h2><%= @post.shop %></h2>
    </div>

    <div class="photo">
      <% if @post.image.attached? %>
        <%= image_tag @post.image, size: "400x400" %>
      <% else %>
        <%= image_tag asset_path('no_image.jpg'), size: "400x400" %>
      <% end %>
    </div>

    <div class="text col-lg-12">
      <%= @post.text %>
    </div>

    <div class="btn-delete">
      <%= link_to "投稿削除", admin_post_path(@post.id), method: :delete, data:{confirm: " [確認]　削除しますか?"}, class: 'btn col-lg-12 btn-outline-dark' %>
    </div>
  </div>

  <div class="row">
    <h3>コメント</h3>
  </div>
  <div class="row">
    <div class="comment col-lg-12">
      <table class="table table-hover table-inverse col-md-12 px-auto">
        <thead class="text-center">
          <tr>
            <th>コメント投稿者</th>
            <th>コメント内容</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @comments.each do |comment| %>
            <tr>
              <td><% if comment.customer.image.attached? %>
                    <%= image_tag comment.customer.image, size: "50x50" %>
                  <% else %>
                    <%= image_tag asset_path('no_image.jpg'), size: "50x50" %>
                  <% end %>
                  　　<%= comment.customer.user_name %></td>
              <td><%= comment.comment %></td>
              <td class="text-center"><%= link_to "削除", public_post_comment_path(@post, comment), method: :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>