config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  passwords: "public/passwords",
  sessions: 'public/sessions'
  }


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get 'about' => 'public/homes#about', as: 'about'
  get 'admin' => 'admin/homes#top'


  namespace :public do
    resources :homes, only: [:top, :about] do
    end
    resources :posts, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
      #投稿検索機能
      get 'search' => 'posts#search', on: :collection
      #ブックマーク機能(good)
      post 'good/:id' => 'goods#create', as: 'create_good'
      delete 'good/:id' => 'goods#destroy', as: 'destroy_good'
      #ブックマーク機能(go)
      post 'go/:id' => 'gos#create', as: 'create_go'
      get 'go/:id' => 'gos#index', as: 'index_go'
      delete 'go/:id' => 'gos#destroy', as: 'destroy_go'
      #コメント機能
      resources :comments, only: [:create, :destroy]
      #地図機能
      get 'map' => 'posts#map'
    end
    #ゲストログイン機能
    devise_scope :customer do
      post "customers/guest_sign_in", to: "sessions#guest_sign_in"
    end
    resources :customers, only: [:show, :edit, :update] do
      get 'inf_show' => 'customers#inf_show'
      get 'inf_edit' => 'customers#inf_edit'
      patch 'inf_update' => 'customers#inf_update'
      #ユーザー検索機能
      get 'search' => 'customers#search', on: :collection
      #退会機能
      get 'confirm' => 'customers#confirm'
      patch 'withdrow' => 'customers#withdrow'
    end
    resources :follows, only: [:create, :destroy] do
      get 'follower/:id' => 'follows#follower', as: 'follower'
      get 'followed/:id' => 'follows#followed', as: 'followed'
    end
    resources :goods, only: [:index] do
    end
    resources :goes, only: [:index] do
    end
    resources :genres, only: [:index] do
    end
 end

namespace :admin do
  resources :homes, only: [:top] do
  end
  resources :posts, only: [:index, :show, :destroy] do
  end
  resources :customers, only: [:index, :show, :edit, :update] do
  end
  resources :genres, only: [:index, :create, :edit, :update] do
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

#コメント機能
  belongs_to :customer
  belongs_to :post

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

#コメント機能・いいね・行ってみたい
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :goods
  has_many :gos

  def good_find(post_id)
    goods.where(post_id: post_id).exists?
  end

  def go_find(post_id)
    gos.where(post_id: post_id).exists?
  end

#フォロー機能
  # フォローをした、されたの関係
  has_many :follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followeds, through: :follows, source: :followed
  has_many :followers, through: :reverse_of_follows, source: :follower

  #フォローしたときの処理
  def followed(customer_id)
    # binding.pry
    follows.create(followed_id: customer_id)
  end
  # フォローを外すときの処理
  def unfollow(customer_id)

    follows.find_by(followed_id: customer_id).destroy
  end
  # フォローしているか判定
  def followed?(customer)
    followeds.include?(customer)
  end


#ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
    end
  end


#ユーザー検索機能
  def self.search(keyword)
    where(["last_name like? OR first_name like? OR user_name like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

end

app/models/follow.rb
class Follow < ApplicationRecord

  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"

end

app/models/genre.rb
class Genre < ApplicationRecord

  belongs_to :posts

end

app/models/go.rb
class Go < ApplicationRecord
  
  belongs_to :customer
  belongs_to :post
  
end

app/models/good.rb
class Good < ApplicationRecord

  belongs_to :customer
  belongs_to :post
  
  

end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :image

#コメント機能・いいね・行ってみたい
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :goods
  has_many :gos
  has_many :genres

#投稿検索機能
  def self.search(keyword)
    where(["shop like? OR address like?", "%#{keyword}%", "%#{keyword}%"])
  end

#map機能
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def new
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def index
    @genre = Genre.new
    @genres = Genre.all

  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

    def genre_params
        params.require(:genre).permit(:name)
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def index
    @posts = Post.page(params[:page]).per(8)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", admin_posts_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ryokou</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
        <h2 class="logo"><%= image_tag asset_path('logo10.jpg') %></h2>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

          <% if customer_signed_in? %>
              <li>
                <%= link_to "アカウント検索", search_public_customers_path, class: 'btn btn-outline-dark' %>
              </li>
              <li>
                <%= link_to "ログアウト",  destroy_customer_session_path, method: :delete, data:{confirm: " [確認]　ログアウトしますか?"}, class: 'btn btn-outline-dark' %>
              </li>
          <% elsif admin_signed_in? %>
             <li>
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-outline-dark' %>
             </li>
             <li>
              <%= link_to "投稿一覧", admin_posts_path, class: 'btn btn-outline-dark' %>
             </li>
             <li>
              <%= link_to "会員一覧", admin_customers_path, class: 'btn btn-outline-dark' %>
             </li>
          <% else %>
            <li>
              <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-dark' %>
            </li>
            <li>
              <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-outline-dark' %>
            </li>
            <li>
              <%= link_to 'ゲストログイン', public_customers_guest_sign_in_path, method: :post, class: 'btn btn-outline-dark' %>
            </li>
            <li>
              <%= link_to '管理者用', new_admin_session_path, class: 'btn btn-outline-dark' %>
            </li>
          <% end %>
          </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
       <%= yield %>
    </main>


    <footer class="border-top shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
      <% if customer_signed_in? %>
        <li>
          <%= link_to "新規投稿", new_public_post_path, class: 'btn btn-outline-dark' %>
        </li>
        <li>
          <%= link_to "投稿一覧", public_posts_path, class: 'btn btn-outline-dark' %>
        </li>
        <li>
          <%= link_to "投稿検索", search_public_posts_path, class: 'btn btn-outline-dark' %>
        </li>
        <li>
          <%= link_to "プロフィール", public_customer_path(current_customer), class: 'btn btn-outline-dark' %>
        </li>

        </div>
      <% else %>

      <% end %>
      </ul>
          </div>
        </div>
      </nav>
    </footer>
  </body>
</html>